# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the yr-main branch
  push:
    branches: [ yr-main ]
  pull_request:
    branches: [ yr-main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: useDocker
        uses: z4nyx/docker:@latest
       
      - run: 
           git config --global user.name "YashRahate"
           git config --global user.email "yrahate7@gmail.com"
           git config --global color.ui false
           bash build.sh
    
